# This section declares settings for the database.
[database]
# database for caching (support Redis only)
cache_store = "redis://127.0.0.1:6379/2?database=2"
# database for persist data (support MySQL/MongoDB)
data_store = "mysql://root:123456@tcp(localhost:3306)/gorse?parseTime=true"


